
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    #columns:
      #- name: id
        #description: "The primary key for this table"
        #tests:
          #- unique
          #- not_null
  - name: my_second_dbt_model
    description: "Second dbt model"
  - name: addresses_stg
    description: "Staging table which contains the address of each customer."
  - name: events_stg
    description: "Staging table which contains events from all customer actions on the booking flow."
  - name: order_items_stg
    description: "Staging table which contains product types & product quantities per order_id."
  - name: orders_stg
    description: "Staging table which contains the orders from customers."
  - name: products_stg
    description: "Staging table which contains name, price & quantity in stock for each product type."
  - name: promos_stg
    description: "Staging table which contains discount types and % discount for each promotional offer."
  - name: users_stg
    description: "Staging table which contains all our customers."
        
        