select
  u.user_uuid,
  u.first_name as user_first_name,
  u.last_name as user_last_name,
  u.email as user_email,
  u.phone_number as user_phone_number,
  u.created_at as user_creation_date,
  u.updated_at as user_last_update_date,
  a.address as user_address,
  a.zipcode as user_zipcode,
  a.state as user_state,
  a.country as user_country,
  uo.user_first_web_activity_date,
  uo.user_last_web_activity_date,
  uo.user_days_since_last_web_activity,
  uo.user_web_sessions_count,
  uo.user_web_sessions_with_page_viewed,
  uo.user_web_sessions_with_product_added_to_cart,
  uo.user_web_sessions_with_checkout,
  uo.user_first_order_date,
  uo.user_last_order_date,
  uo.user_days_since_last_order,
  uo.user_orders_count,
  uo.order_product_types,
  uo.order_quantity_of_products     
from {{ ref('stg_users') }} u
left join {{ ref('stg_addresses') }} a
on u.address_uuid=a.address_uuid
left join {{ ref('int_user_orders_metrics') }} uo
on u.user_uuid=uo.user_uuid
group by 
  u.user_uuid,
  u.first_name,
  u.last_name,
  u.email,
  u.phone_number,
  u.created_at,
  u.updated_at,
  u.address_uuid,
  a.address,
  a.zipcode,
  a.state,
  a.country,
  uo.user_first_web_activity_date,
  uo.user_last_web_activity_date,
  uo.user_days_since_last_web_activity,
  uo.user_web_sessions_count,
  uo.user_web_sessions_with_page_viewed,
  uo.user_web_sessions_with_product_added_to_cart,
  uo.user_web_sessions_with_checkout,
  uo.user_first_order_date,
  uo.user_last_order_date,
  uo.user_days_since_last_order,
  uo.user_orders_count,
  uo.order_product_types,
  uo.order_quantity_of_products