
version: 2

models:
  - name: stg_addresses
    description: "Staging table which contains the address of each customer."
  - name: stg_events
    description: "Staging table which contains events from all customer actions on the booking flow."
  - name: stg_order_items
    description: "Staging table which contains product types & product quantities per order_id."
  - name: stg_orders
    description: "Staging table which contains the orders from customers."
  - name: stg_products
    description: "Staging table which contains name, price & quantity in stock for each product type."
  - name: stg_promos
    description: "Staging table which contains discount types and % discount for each promotional offer."
  - name: stg_users
    description: "Staging table which contains all our customers."
        
        